services:
  app1:
    build: ./app
    container_name: fastapi_app1
    expose:
      - "8000"

  app2:
    build: ./app
    container_name: fastapi_app2
    expose:
      - "8000"

  haproxy:
    image: haproxy:2.9
    container_name: haproxy_gateway
    expose:
      - "80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx  
    depends_on:
      - haproxy

